services:
  backend:
    build:
      context: ./backend
    image: teodorriyce/docker-project-backend:latest
    container_name: momo-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - momo-network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

  frontend:
    build:
      context: ./frontend
    image: teodorriyce/docker-project-frontend:latest
    container_name: momo-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - momo-network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 256M
    volumes:
      - nginx-cache:/var/cache/nginx:rw
      - nginx-run:/var/run:rw

networks:
  momo-network:

volumes:
    nginx-cache:
    nginx-run:
